### ISSUE TITLE
Research opportunity of Workflowy integration

### ISSUE THREAD

**Issue by FhtagnEast** [lis-press/greeb-bot#23]
- [x] Describe the way to get WorkFlowy session
- [x] Parametrize the sessionId via parameters
- [x] Create the methods that get the tree structure in a readable format
- [x] Create an example, how to work with WorkFlowy structure: get some metrics based on the structure of JSON

**Comment by eliseealex** [comment]
There are two main queries, login and get full information:
`https://workflowy.com/api/auth` You need to send post form data with your email and password.
You get sessionid as a result. Not sure the TTL of this sessionid.

Then you can make queries with this sessionid, to get the full hierarchy you need to send the query to:
https://workflowy.com/get_initialization_data?client_version=18 -> you may use newer version and check it in the browser.

Code snippet:
```kotlin
val metaUrl = "https://workflowy.com/get_initialization_data?client_version=18"
val httpGet = HttpGet(metaUrl)
httpGet.addHeader("cookie", "sessionid=SECRET_SESSION_ID")
val response = httpClient.execute(httpGet)
val res = EntityUtils.toString(response.entity)
```

**Comment by eliseealex** [comment]
Quite a long time spent searching how to work with encoding, turns out you need to convert to json object to work correctly with cyrrilic symbols:
```kotlin
val result = JSONObject(s)
```
